# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generator_service_pb2 as generator__service__pb2


class GeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallRemoteMethod = channel.stream_stream(
                '/protocol.GeneratorService/CallRemoteMethod',
                request_serializer=generator__service__pb2.MsgPickleDumps.SerializeToString,
                response_deserializer=generator__service__pb2.MsgPickleDumps.FromString,
                )


class GeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CallRemoteMethod(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallRemoteMethod': grpc.stream_stream_rpc_method_handler(
                    servicer.CallRemoteMethod,
                    request_deserializer=generator__service__pb2.MsgPickleDumps.FromString,
                    response_serializer=generator__service__pb2.MsgPickleDumps.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocol.GeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CallRemoteMethod(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/protocol.GeneratorService/CallRemoteMethod',
            generator__service__pb2.MsgPickleDumps.SerializeToString,
            generator__service__pb2.MsgPickleDumps.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
