# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17generator_service.proto\x12\x08protocol\"I\n\x0eMsgPickleDumps\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x17\n\nis_chunked\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_is_chunked2^\n\x10GeneratorService\x12J\n\x10\x43\x61llRemoteMethod\x12\x18.protocol.MsgPickleDumps\x1a\x18.protocol.MsgPickleDumps(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MSGPICKLEDUMPS']._serialized_start=37
  _globals['_MSGPICKLEDUMPS']._serialized_end=110
  _globals['_GENERATORSERVICE']._serialized_start=112
  _globals['_GENERATORSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
